# remote_theme: pages-themes/architect@v0.2.0
# plugins:
# - jekyll-remote-theme
theme: jekyll-theme-architect
title: "Build a PC"
description: "CPT project for AP Computer Science Principles."
gitorg: "https://github.com/A1234l/Build-a-PC"
google_analytics:
